version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python /app/agent.py"
